export const languages = {
  english: {
    home: 'Home',
    shop: 'Shop',
    cart: 'Cart',
    profile: 'Profile',
    orders: 'Orders',
    wishList: 'Wish List',
    about: 'About',
    settings: 'Settings',
    logout: 'Log out',
    login: 'Log in',
    products: 'Products',
    appPreferences: 'App Preferences',
    user: 'User',
    hello: 'Hello',
    made: 'Made',
    with: 'with',
    search: 'search',
    name: 'Name',
    email: 'Email',
    address: 'Address',
    change: 'Change',
    password: 'Password',
    delete: 'Delete',
    account: 'Account',
    //translated till here
  },
  chinese: {
    home: '家',
    shop: '店',
    cart: '大车',
    profile: '轮廓',
    orders: '命令',
    wishList: '愿望清单',
    about: '关于',
    settings: '设定值',
    logout: '登出',
    login: '登录',
    products: '产品展示',
    appPreferences: '应用程式偏好设定',
    user: '用户',
    hello: '你好',
    made: '制作',
    with: '与',
    search: '搜索',
    name: '名称',
    email: '电子邮件',
    address: '地址',
    change: '更改',
    password: '密码',
    delete: '删除',
    account: '帐户',
  },
  german: {
    home: 'Zuhause',
    shop: 'Geschäft',
    cart: 'Wagen',
    profile: 'Profil',
    orders: 'Aufträge',
    wishList: 'Wunschzettel',
    about: 'Über',
    settings: 'die Einstellungen',
    logout: 'Ausloggen',
    login: 'Anmeldung',
    products: 'Produkte',
    appPreferences: 'App-Einstellungen',
    user: 'Benutzer',
    hello: 'Hallo',
    made: 'Gemacht',
    with: 'mit',
    search: 'Suche',
    name: 'Name',
    email: 'Email',
    address: 'Adresse',
    change: 'Veränderung',
    password: 'Passwort',
    delete: 'Löschen',
    account: 'Konto',
  },
};
