export const pokemons = [
  {
    id: 1,
    name: 'Bulbasaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '6.9 kg',
    Height: '0.7 m',
    star: 3,
  },
  {
    id: 2,
    name: 'Ivysaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '13 kg',
    Height: '1 m',
    star: 3,
  },
  {
    id: 3,
    name: 'Venusaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '100 kg',
    Height: '2 m',
    star: 3,
  },
  {
    id: 4,
    name: 'Charmander',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '8.5 kg',
    Height: '0.6 m',
    star: 4,
  },
  {
    id: 5,
    name: 'Charmeleon',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '19 kg',
    Height: '1.1 m',
    star: 4,
  },
  {
    id: 6,
    name: 'Charizard',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '90.5 kg',
    Height: '1.7 m',
    star: 4,
  },
  {
    id: 7,
    name: 'Squirtle',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '9 kg',
    Height: '0.5 m',
    star: 3,
  },
  {
    id: 8,
    name: 'Wartortle',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '22.5 kg',
    Height: '1 m',
    star: 3,
  },
  {
    id: 9,
    name: 'Blastoise',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '85.5 kg',
    Height: '1.6 m',
    star: 3,
  },
  {
    id: 10,
    name: 'Pikachu',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Electric',
    weight: '6 kg',
    Height: '0.4 m',
    star: 5,
  },
];
