export const pokemons = [
  {
    id: 1,
    name: 'Bulbasaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '6.9 kg',
    Height: '0.7 m',
    star: 3,
  },
  {
    id: 2,
    name: 'Ivysaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '13 kg',
    Height: '1 m',
    star: 3,
  },
  {
    id: 3,
    name: 'Venusaur',
    image: require('../assets/pokemons/bulba1.png'),
    type: 'grass',
    weight: '100 kg',
    Height: '2 m',
    star: 3,
  },
  {
    id: 4,
    name: 'Charmander',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '8.5 kg',
    Height: '0.6 m',
    star: 4,
  },
  {
    id: 5,
    name: 'Charmeleon',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '19 kg',
    Height: '1.1 m',
    star: 4,
  },
  {
    id: 6,
    name: 'Charizard',
    image: require('../assets/pokemons/char3.png'),
    type: 'Fire',
    weight: '90.5 kg',
    Height: '1.7 m',
    star: 4,
  },
  {
    id: 7,
    name: 'Squirtle',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '9 kg',
    Height: '0.5 m',
    star: 3,
  },
  {
    id: 8,
    name: 'Wartortle',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '22.5 kg',
    Height: '1 m',
    star: 3,
  },
  {
    id: 9,
    name: 'Blastoise',
    image: require('../assets/pokemons/squrtle2.png'),
    type: 'Water',
    weight: '85.5 kg',
    Height: '1.6 m',
    star: 3,
  },
  {
    id: 10,
    name: 'Pikachu',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Electric',
    weight: '6 kg',
    Height: '0.4 m',
    star: 5,
  },
  {
    id: 11,
    name: 'Caterpie',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '2.9 kg',
    Height: '0.3 m',
    star: 5,
  },
  {
    id: 12,
    name: 'Metapod',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '9.9 kg',
    Height: '0.7 m',
    star: 5,
  },
  {
    id: 13,
    name: 'Butterfree',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '32 kg',
    Height: '1.1 m',
    star: 5,
  },
  {
    id: 14,
    name: 'Weedle',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '3.2 kg',
    Height: '0.3 m',
    star: 5,
  },
  {
    id: 15,
    name: 'Kakuna',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '10 kg',
    Height: '0.6 m',
    star: 5,
  },
  {
    id: 16,
    name: 'Beedrill',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Bug',
    weight: '29.5 kg',
    Height: '1 m',
    star: 5,
  },
  {
    id: 17,
    name: 'Pidgey',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '1.8 kg',
    Height: '0.3 m',
    star: 5,
  },
  {
    id: 18,
    name: 'Pidgeotto',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '30 kg',
    Height: '1.1 m',
    star: 5,
  },
  {
    id: 19,
    name: 'Pidgeot',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '39.5 kg',
    Height: '1.5 m',
    star: 5,
  },
  {
    id: 20,
    name: 'Rattata',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Normal',
    weight: '3.5 kg',
    Height: '0.3 m',
    star: 5,
  },
  {
    id: 21,
    name: 'Raticate',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Normal',
    weight: '18.5 kg',
    Height: '0.7 m',
    star: 5,
  },
  {
    id: 22,
    name: 'Spearow',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '2 kg',
    Height: '0.3 m',
    star: 5,
  },
  {
    id: 23,
    name: 'Fearow',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '38 kg',
    Height: '1.2 m',
    star: 5,
  },
  {
    id: 24,
    name: 'Ekans',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Poison',
    weight: '6.9 kg',
    Height: '2 m',
    star: 5,
  },
  {
    id: 25,
    name: 'Arbok',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Flying',
    weight: '65 kg',
    Height: '3.5 m',
    star: 5,
  },
  {
    id: 26,
    name: 'Raichu',
    image: require('../assets/pokemons/pika1.png'),
    type: 'Electric',
    weight: '30 kg',
    Height: '0.8 m',
    star: 5,
  },
];
